name: CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

env:
  CONFIGURATION: Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c ${{ env.CONFIGURATION }}
      
    - name: Test
      run: dotnet test --no-build -c ${{ env.CONFIGURATION }}

    - name: Publish
      run: dotnet publish ChildObjectsEf.Api/ChildObjectsEf.Api.csproj --configuration ${{ env.CONFIGURATION }} -o ChildObjectsEf.Api/bin/publish

    - name: Create docker image
      run: docker build -f ChildObjectsEf.Api/Dockerfile -t childobjectsef:1.0.1 .

  codeql-analysis:    
    name: CodeQL analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp
        
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  github-package-docker-push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    name: GitHub package docker push
    needs: [build, codeql-analysis]
    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Publish
      run: dotnet publish ChildObjectsEf.Api/ChildObjectsEf.Api.csproj --configuration ${{ env.CONFIGURATION }} -o ChildObjectsEf.Api/bin/publish

    - name: Create docker image
      run: docker build -f ChildObjectsEf.Api/Dockerfile -t ghcr.io/arnab-developer/childobjectsef/childobjectsef:1.0.1 .

    - name: GitHub Container Registry login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push docker image
      run: docker push ghcr.io/arnab-developer/childobjectsef/childobjectsef:1.0.1

  dockerhub-push:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    name: Dockerhub push
    needs: [build, codeql-analysis]    
    environment:
      name: Dockerhub
      url: https://hub.docker.com/r/45862391/childobjectsef

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Publish
      run: dotnet publish ChildObjectsEf.Api/ChildObjectsEf.Api.csproj --configuration ${{ env.CONFIGURATION }} -o ChildObjectsEf.Api/bin/publish

    - name: Create docker image
      run: docker build -f ChildObjectsEf.Api/Dockerfile -t 45862391/childobjectsef:1.0.1 .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ 45862391 }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Push docker image
      run: docker push 45862391/childobjectsef:1.0.1